# Session 10 — Pandas Series and DataFrame Basics
### Module 3: Introduction to Data Handling with Pandas

This notebook covers:
- What pandas is and why it is used
- Creating and working with pandas **Series**
- Creating and working with pandas **DataFrame**
- Indexing, selecting, and modifying data
- A hands-on practice exercise

## 1. What is Pandas?

Pandas is an open-source Python library used for data manipulation and analysis. It is built on top of **NumPy** and is designed to work with **structured/tabular data** (similar to an Excel sheet or SQL table).

**Why use pandas?**
- Labeled data — rows and columns have names
- Fast vectorized operations
- Handles missing data gracefully
- Rich set of tools for reading, cleaning, transforming, and analyzing data

In [1]:
import pandas as pd
import numpy as np

## 2. Two Core Data Structures

| Structure | Dimensionality | Analogy |
|---|---|---|
| **Series** | 1-D | Single column of Excel / a list with labels |
| **DataFrame** | 2-D | Full Excel sheet / SQL table |

> A DataFrame is essentially a collection of Series sharing the same index.

## 3. Creating a Series

In [2]:
# From a list
s1 = pd.Series([10, 20, 30, 40])
print(s1)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
# From a list with custom index
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s2)

a    10
b    20
c    30
d    40
dtype: int64

In [4]:
# From a dictionary (keys become index)
s3 = pd.Series({'math': 85, 'science': 90, 'english': 78})
print(s3)

math       85
science    90
english    78
dtype: int64

In [5]:
# From a scalar value (broadcast)
s4 = pd.Series(5, index=[0, 1, 2, 3])
print(s4)

0    5
1    5
2    5
3    5
dtype: int64

**Key observations:**
- Default index starts at 0 (like array position)
- Each Series has a **dtype** (int64, float64, object, etc.)
- Series = values + index (unlike a plain Python list)

## 4. Series Attributes

In [6]:
print(s2.values)   # underlying numpy array
print(s2.index)    # index object
print(s2.dtype)    # data type of elements
print(s2.shape)    # tuple showing size
print(s2.size)     # number of elements
print(s2.name)     # optional name of the series

[10 20 30 40]
Index(['a', 'b', 'c', 'd'], dtype='object')
int64
(4,)
4
None

In [45]:
import pandas as pd

ss11 = pd.Series([10, 20, 30], name="Marks")

print(ss11.name)

Marks

In [46]:
s2

a    10
b    20
c    30
d    40
dtype: int64

## 5. Indexing and Selecting from a Series

In [7]:
print(s2['a'])       # label-based access
print(s2.loc['b'])   # explicit label-based access
print(s2.iloc[1])    # explicit position-based access

10
20
20

In [8]:
print(s2['a':'c'])   # slicing by label (inclusive of end)
print(s2[0:2])       # slicing by position (exclusive of end)

a    10
b    20
c    30
dtype: int64
a    10
b    20
dtype: int64

**Important note:**
- `.loc[]` → label-based
- `.iloc[]` → integer position-based

This distinction is important and applies to DataFrames as well.

## 6. Basic Series Operations

In [9]:
print(s2 + 5)          # broadcasting
print(s2 * 2)
print(s2[s2 > 15])     # boolean filtering
print(s2.sum(), s2.mean(), s2.max(), s2.min())

a    15
b    25
c    35
d    45
dtype: int64
a    20
b    40
c    60
d    80
dtype: int64
b    20
c    30
d    40
dtype: int64
100 25.0 40 10

## 7. What is a DataFrame?

A DataFrame is a 2-dimensional labeled data structure with columns that can hold different data types. It can be thought of as a dictionary of Series objects that share a common index.

## 8. Creating a DataFrame

In [10]:
# From a dictionary of lists
data = {
    'Name': ['Asha', 'Ravi', 'Meena', 'Karan'],
    'Age': [23, 25, 22, 24],
    'City': ['Chennai', 'Delhi', 'Mumbai', 'Pune'],
    'Marks': [85, 78, 92, 88]
}
df = pd.DataFrame(data)
df

    Name  Age     City  Marks
0   Asha   23  Chennai     85
1   Ravi   25    Delhi     78
2  Meena   22   Mumbai     92
3  Karan   24     Pune     88

In [11]:
# From a list of dictionaries
records = [
    {'Name': 'Asha', 'Age': 23},
    {'Name': 'Ravi', 'Age': 25}
]
df2 = pd.DataFrame(records)
df2

   Name  Age
0  Asha   23
1  Ravi   25

In [12]:
# From a list of lists with explicit columns
df3 = pd.DataFrame(
    [[1, 'A'], [2, 'B']],
    columns=['ID', 'Grade']
)
df3

   ID Grade
0   1     A
1   2     B

In [13]:
# From a NumPy array
df4 = pd.DataFrame(np.arange(1, 13).reshape(3, 4), columns=['W', 'X', 'Y', 'Z'])
df4

   W   X   Y   Z
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [44]:
df

    Name  Age  Score  Passed  Marks_Percent
0   Asha   24     85    True           85.0
1   Ravi   26     78   False           78.0
2  Meena   23     92    True           92.0
3  Karan   25     88    True           88.0

## 9. DataFrame Attributes

In [14]:
print(df.shape)      # (rows, columns)
print(df.columns)    # column labels
print(df.index)      # row labels
print(df.dtypes)     # data type of each column
print(df.size)       # total number of elements
print(df.ndim)       # number of dimensions (2)

(4, 4)
Index(['Name', 'Age', 'City', 'Marks'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
Name     object
Age       int64
City     object
Marks     int64
dtype: object
16
2

## 10. Inspecting a DataFrame

In [15]:
df.head()       # first 5 rows (default)

    Name  Age     City  Marks
0   Asha   23  Chennai     85
1   Ravi   25    Delhi     78
2  Meena   22   Mumbai     92
3  Karan   24     Pune     88

In [16]:
df.head(2)      # first 2 rows

   Name  Age     City  Marks
0  Asha   23  Chennai     85
1  Ravi   25    Delhi     78

In [17]:
df.tail(3)      # last 3 rows (only 4 rows exist here)

    Name  Age    City  Marks
1   Ravi   25   Delhi     78
2  Meena   22  Mumbai     92
3  Karan   24    Pune     88

In [18]:
df.info()       # summary: dtypes, non-null counts, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Marks   4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [19]:
df.describe()   # statistical summary of numeric columns

             Age      Marks
count   4.000000   4.000000
mean   23.500000  85.750000
std     1.290994   5.909033
min    22.000000  78.000000
25%    22.750000  83.250000
50%    23.500000  86.500000
75%    24.250000  89.000000
max    25.000000  92.000000

**Tip:** It is a good habit to run `.info()` and `.describe()` first when exploring any new dataset. This will be used again in later sessions on Exploratory Data Analysis (EDA).

## 11. Selecting Columns

In [20]:
df['Name']              # single column -> returns a Series

0     Asha
1     Ravi
2    Meena
3    Karan
Name: Name, dtype: object

In [21]:
df[['Name', 'Age']]     # multiple columns -> returns a DataFrame

    Name  Age
0   Asha   23
1   Ravi   25
2  Meena   22
3  Karan   24

In [22]:
df.Name                 # attribute-style access (works if no spaces/special characters)

0     Asha
1     Ravi
2    Meena
3    Karan
Name: Name, dtype: object

## 12. Selecting Rows

In [23]:
df.loc[0]           # row by label

Name        Asha
Age           23
City     Chennai
Marks         85
Name: 0, dtype: object

In [24]:
df.iloc[0]           # row by position

Name        Asha
Age           23
City     Chennai
Marks         85
Name: 0, dtype: object

In [25]:
df.loc[0:2]          # label-based slicing (inclusive)

    Name  Age     City  Marks
0   Asha   23  Chennai     85
1   Ravi   25    Delhi     78
2  Meena   22   Mumbai     92

In [26]:
df.iloc[0:2]         # position-based slicing (exclusive)

   Name  Age     City  Marks
0  Asha   23  Chennai     85
1  Ravi   25    Delhi     78

In [27]:
df.loc[1, 'Name']            # specific cell by label

'Ravi'

In [28]:
df.iloc[1, 0]                 # specific cell by position

'Ravi'

In [29]:
df.loc[0:2, ['Name', 'Age']]  # subset of rows and columns

    Name  Age
0   Asha   23
1   Ravi   25
2  Meena   22

## 13. Adding and Modifying Columns

In [30]:
df['Passed'] = df['Marks'] >= 80          # new boolean column
df

    Name  Age     City  Marks  Passed
0   Asha   23  Chennai     85    True
1   Ravi   25    Delhi     78   False
2  Meena   22   Mumbai     92    True
3  Karan   24     Pune     88    True

In [31]:
df['Marks_Percent'] = df['Marks'] / 100 * 100
df

    Name  Age     City  Marks  Passed  Marks_Percent
0   Asha   23  Chennai     85    True           85.0
1   Ravi   25    Delhi     78   False           78.0
2  Meena   22   Mumbai     92    True           92.0
3  Karan   24     Pune     88    True           88.0

In [32]:
df['Age'] = df['Age'] + 1                 # modify existing column
df

    Name  Age     City  Marks  Passed  Marks_Percent
0   Asha   24  Chennai     85    True           85.0
1   Ravi   26    Delhi     78   False           78.0
2  Meena   23   Mumbai     92    True           92.0
3  Karan   25     Pune     88    True           88.0

In [33]:
df.rename(columns={'Marks': 'Score'}, inplace=True)
df

    Name  Age     City  Score  Passed  Marks_Percent
0   Asha   24  Chennai     85    True           85.0
1   Ravi   26    Delhi     78   False           78.0
2  Meena   23   Mumbai     92    True           92.0
3  Karan   25     Pune     88    True           88.0

## 14. Dropping Rows/Columns

In [34]:
df.drop('Passed', axis=1)              # drop column (axis=1)

    Name  Age     City  Score  Marks_Percent
0   Asha   24  Chennai     85           85.0
1   Ravi   26    Delhi     78           78.0
2  Meena   23   Mumbai     92           92.0
3  Karan   25     Pune     88           88.0

In [35]:
df.drop(0, axis=0)                      # drop row (axis=0)

    Name  Age    City  Score  Passed  Marks_Percent
1   Ravi   26   Delhi     78   False           78.0
2  Meena   23  Mumbai     92    True           92.0
3  Karan   25    Pune     88    True           88.0

In [36]:
df.drop(columns=['City'], inplace=True) # inplace modification
df

    Name  Age  Score  Passed  Marks_Percent
0   Asha   24     85    True           85.0
1   Ravi   26     78   False           78.0
2  Meena   23     92    True           92.0
3  Karan   25     88    True           88.0

## 15. Basic Filtering (Preview)

Filtering, sorting, and grouping will be covered in depth in the next session. This is a short preview of what DataFrames can do.

In [37]:
df[df['Age'] > 23]

    Name  Age  Score  Passed  Marks_Percent
0   Asha   24     85    True           85.0
1   Ravi   26     78   False           78.0
3  Karan   25     88    True           88.0

In [38]:
df[(df['Age'] > 22) & (df['Score'] > 80)]

    Name  Age  Score  Passed  Marks_Percent
0   Asha   24     85    True           85.0
2  Meena   23     92    True           92.0
3  Karan   25     88    True           88.0

## 16. Series vs DataFrame — Conversion

In [39]:
s = df['Age']            # DataFrame column -> Series
s

0    24
1    26
2    23
3    25
Name: Age, dtype: int64

In [40]:
df_new = s.to_frame()    # Series -> DataFrame
df_new

   Age
0   24
1   26
2   23
3   25

## 17. Hands-on Practice Exercise

Using the sample dataset below, complete the following tasks:

1. Create a DataFrame with at least 5 rows and 4 columns (mixed data types)
2. Print `.shape`, `.dtypes`, `.info()`, `.describe()`
3. Select a single column and convert it to a Series
4. Select 2 columns and 3 rows using both `.loc` and `.iloc`
5. Add a new calculated column
6. Filter the DataFrame based on a condition
7. Drop one column and one row

In [41]:
# Sample dataset for practice
students = {
    'Name': ['Aditi', 'Bala', 'Chitra', 'Dev', 'Esha'],
    'Age': [21, 22, 21, 23, 22],
    'Department': ['CS', 'ECE', 'CS', 'ME', 'ECE'],
    'CGPA': [8.5, 7.9, 9.1, 7.2, 8.8]
}
df_students = pd.DataFrame(students)
df_students

     Name  Age Department  CGPA
0   Aditi   21         CS   8.5
1    Bala   22        ECE   7.9
2  Chitra   21         CS   9.1
3     Dev   23         ME   7.2
4    Esha   22        ECE   8.8

In [42]:
# Write your solutions to the exercise below

## Key Terms Glossary

| Term | Meaning |
|---|---|
| Series | 1-dimensional labeled array |
| DataFrame | 2-dimensional labeled tabular structure |
| Index | Labels for rows |
| dtype | Data type of column/Series values |
| loc | Label-based indexer |
| iloc | Integer position-based indexer |
| axis=0 | Refers to rows |
| axis=1 | Refers to columns |

## Common Mistakes to Avoid

- Confusing `.loc[0:2]` (inclusive) with `.iloc[0:2]` (exclusive)
- Forgetting `axis=1` when dropping columns
- Using `df['col1', 'col2']` instead of `df[['col1', 'col2']]` for multiple columns
- Not using `inplace=True` or reassigning the result, then wondering why changes don't persist

## Homework / Practice Assignment

- Create a DataFrame of at least 10 records related to any real-world scenario (e.g., movies, products, employees)
- Perform all operations covered in this notebook
- Come prepared with 2 questions/doubts for the next session's recap