# Session 11 — Reading CSV Files, Viewing Data, Selecting Rows and Columns
### Module 3: Introduction to Data Handling with Pandas

In [1]:
import pandas as pd
import numpy as np

## 1. Quick Recap

- **Series** → 1-D labeled array
- **DataFrame** → 2-D labeled table (collection of Series with a shared index)
- `.loc[]` → label-based selection
- `.iloc[]` → position-based selection

## 2. Setting Up Sample Data Files

In [2]:
# Standard, clean CSV file
data = {
    'StudentID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Aditi', 'Bala', 'Chitra', 'Dev', 'Esha', 'Farhan', 'Gita', 'Harish'],
    'Department': ['CS', 'ECE', 'CS', 'ME', 'ECE', 'CS', 'ME', 'ECE'],
    'Age': [21, 22, 21, 23, 22, 24, 21, 23],
    'CGPA': [8.5, 7.9, 9.1, 7.2, 8.8, 6.9, 8.0, 7.5],
    'City': ['Chennai', 'Delhi', 'Mumbai', 'Pune', 'Chennai', 'Bangalore', 'Delhi', 'Chennai']
}
df_temp = pd.DataFrame(data)
df_temp.to_csv('students.csv', index=False) # Without index=False (Default: index=True)
print("students.csv created")

students.csv created

In [68]:
nru = pd.read_csv(r"C:\Users\DELL\GR\students.csv")

In [69]:
nru

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
1          2    Bala        ECE   22   7.9      Delhi
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
4          5    Esha        ECE   22   8.8    Chennai
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi
7          8  Harish        ECE   23   7.5    Chennai

In [3]:
# CSV file with a different delimiter (semicolon)
df_temp.to_csv('students_semicolon.csv', index=False, sep=';')
print("students_semicolon.csv created")

students_semicolon.csv created

In [4]:
# CSV file with some missing values
data_missing = data.copy()
data_missing['CGPA'] = [8.5, np.nan, 9.1, 7.2, np.nan, 6.9, 8.0, 7.5]
data_missing['City'] = ['Chennai', 'Delhi', 'Mumbai', None, 'Chennai', 'Bangalore', 'Delhi', 'Chennai']
df_missing_temp = pd.DataFrame(data_missing)
df_missing_temp.to_csv('students_missing.csv', index=False)
print("students_missing.csv created")

students_missing.csv created

In [5]:
# CSV file without a header row
df_temp.to_csv('students_no_header.csv', index=False, header=False)
print("students_no_header.csv created")

students_no_header.csv created

## 3. Reading CSV Files — The Basics

In [6]:
df = pd.read_csv('students.csv')
df

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
1          2    Bala        ECE   22   7.9      Delhi
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
4          5    Esha        ECE   22   8.8    Chennai
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi
7          8  Harish        ECE   23   7.5    Chennai

### Commonly used `read_csv()` parameters

| Parameter | Purpose |
|---|---|
| `filepath_or_buffer` | Path to the CSV file (or a URL) |
| `sep` / `delimiter` | Character used to separate values (default `,`) |
| `header` | Row number to use as column names (default `0`) |
| `names` | Manually provide column names |
| `index_col` | Column to use as the row index |
| `usecols` | Load only specific columns |
| `nrows` | Load only a specific number of rows |
| `skiprows` | Skip a specific number of rows at the start |
| `dtype` | Force specific data types for columns |
| `na_values` | Additional strings to treat as missing values |
| `encoding` | Character encoding of the file (e.g. `'utf-8'`, `'latin1'`) |

## 4. Reading Files with Different Structures

In [7]:
# Reading a semicolon-separated file
df_semi = pd.read_csv('students_semicolon.csv', sep=';')
df_semi

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
1          2    Bala        ECE   22   7.9      Delhi
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
4          5    Esha        ECE   22   8.8    Chennai
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi
7          8  Harish        ECE   23   7.5    Chennai

In [8]:
# Reading a file that has no header row -- must supply column names manually
columns = ['StudentID', 'Name', 'Department', 'Age', 'CGPA', 'City']
df_no_header = pd.read_csv('students_no_header.csv', header=None, names=columns)
df_no_header

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
1          2    Bala        ECE   22   7.9      Delhi
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
4          5    Esha        ECE   22   8.8    Chennai
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi
7          8  Harish        ECE   23   7.5    Chennai

In [9]:
# Reading only specific columns
df_partial = pd.read_csv('students.csv', usecols=['Name', 'Department', 'CGPA'])
df_partial

     Name Department  CGPA
0   Aditi         CS   8.5
1    Bala        ECE   7.9
2  Chitra         CS   9.1
3     Dev         ME   7.2
4    Esha        ECE   8.8
5  Farhan         CS   6.9
6    Gita         ME   8.0
7  Harish        ECE   7.5

In [10]:
# Reading only a limited number of rows (useful for very large files)
df_limited = pd.read_csv('students.csv', nrows=4)
df_limited

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
1          2    Bala        ECE   22   7.9    Delhi
2          3  Chitra         CS   21   9.1   Mumbai
3          4     Dev         ME   23   7.2     Pune

In [62]:
# Using a column as the row index instead of the default 0,1,2...
df_indexed = pd.read_csv('students.csv', index_col='StudentID')
df_indexed

             Name Department  Age  CGPA       City
StudentID
1           Aditi         CS   21   8.5    Chennai
2            Bala        ECE   22   7.9      Delhi
3          Chitra         CS   21   9.1     Mumbai
4             Dev         ME   23   7.2       Pune
5            Esha        ECE   22   8.8    Chennai
6          Farhan         CS   24   6.9  Bangalore
7            Gita         ME   21   8.0      Delhi
8          Harish        ECE   23   7.5    Chennai

In [12]:
# Reading a file that has missing values
df_missing = pd.read_csv('students_missing.csv')
df_missing

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
1          2    Bala        ECE   22   NaN      Delhi
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2        NaN
4          5    Esha        ECE   22   NaN    Chennai
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi
7          8  Harish        ECE   23   7.5    Chennai

In [72]:
# Checking which values pandas automatically detected as missing
df_missing.isnull().sum()

StudentID     0
Name          0
Department    0
Age           0
CGPA          2
City          1
dtype: int64

## 5. Viewing and Inspecting Data

Before doing any analysis, always inspect the data first. This is one of the most important habits to build.

In [74]:
df.sample(3)     # 3 random rows -- useful to spot-check large datasets

   StudentID   Name Department  Age  CGPA     City
6          7   Gita         ME   21   8.0    Delhi
0          1  Aditi         CS   21   8.5  Chennai
3          4    Dev         ME   23   7.2     Pune

In [18]:
df.shape         # (rows, columns)

(8, 6)

In [19]:
df.columns       # column names

Index(['StudentID', 'Name', 'Department', 'Age', 'CGPA', 'City'], dtype='object')

In [20]:
df.index         # row index range

RangeIndex(start=0, stop=8, step=1)

In [21]:
df.dtypes        # data type of each column

StudentID       int64
Name           object
Department     object
Age             int64
CGPA          float64
City           object
dtype: object

In [22]:
df.info()        # summary: dtypes, non-null counts, memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   8 non-null      int64
 1   Name        8 non-null      object
 2   Department  8 non-null      object
 3   Age         8 non-null      int64
 4   CGPA        8 non-null      float64
 5   City        8 non-null      object
dtypes: float64(1), int64(2), object(3)
memory usage: 516.0+ bytes

In [23]:
df.describe()    # statistical summary of numeric columns

       StudentID        Age      CGPA
count    8.00000   8.000000  8.000000
mean     4.50000  22.125000  7.987500
std      2.44949   1.125992  0.775403
min      1.00000  21.000000  6.900000
25%      2.75000  21.000000  7.425000
50%      4.50000  22.000000  7.950000
75%      6.25000  23.000000  8.575000
max      8.00000  24.000000  9.100000

In [24]:
df.describe(include='object')   # statistical summary of text/categorical columns

         Name Department     City
count       8          8        8
unique      8          3        5
top     Aditi         CS  Chennai
freq        1          3        3

In [25]:
df['Department'].unique()       # unique values in a column

array(['CS', 'ECE', 'ME'], dtype=object)

In [26]:
df['Department'].nunique()      # count of unique values

3

In [27]:
df['Department'].value_counts() # frequency of each unique value

Department
CS     3
ECE    3
ME     2
Name: count, dtype: int64

In [28]:
df.memory_usage()               # memory used by each column

Index         132
StudentID      64
Name           64
Department     64
Age            64
CGPA           64
City           64
dtype: int64

## 6. Selecting Columns

In [29]:
df['Name']                          # single column -> Series

0     Aditi
1      Bala
2    Chitra
3       Dev
4      Esha
5    Farhan
6      Gita
7    Harish
Name: Name, dtype: object

In [30]:
df[['Name', 'CGPA']]                # multiple columns -> DataFrame

     Name  CGPA
0   Aditi   8.5
1    Bala   7.9
2  Chitra   9.1
3     Dev   7.2
4    Esha   8.8
5  Farhan   6.9
6    Gita   8.0
7  Harish   7.5

In [31]:
df.Name                             # attribute-style access (works only if column name has no spaces/special characters)

0     Aditi
1      Bala
2    Chitra
3       Dev
4      Esha
5    Farhan
6      Gita
7    Harish
Name: Name, dtype: object

In [32]:
df.filter(items=['Name', 'City'])   # alternative way to select specific columns

     Name       City
0   Aditi    Chennai
1    Bala      Delhi
2  Chitra     Mumbai
3     Dev       Pune
4    Esha    Chennai
5  Farhan  Bangalore
6    Gita      Delhi
7  Harish    Chennai

In [33]:
df.filter(like='e')                 # select columns whose names contain a substring

   StudentID    Name Department  Age
0          1   Aditi         CS   21
1          2    Bala        ECE   22
2          3  Chitra         CS   21
3          4     Dev         ME   23
4          5    Esha        ECE   22
5          6  Farhan         CS   24
6          7    Gita         ME   21
7          8  Harish        ECE   23

In [34]:
# Reordering columns
new_order = ['Name', 'City', 'Department', 'Age', 'CGPA', 'StudentID']
df_reordered = df[new_order]
df_reordered

     Name       City Department  Age  CGPA  StudentID
0   Aditi    Chennai         CS   21   8.5          1
1    Bala      Delhi        ECE   22   7.9          2
2  Chitra     Mumbai         CS   21   9.1          3
3     Dev       Pune         ME   23   7.2          4
4    Esha    Chennai        ECE   22   8.8          5
5  Farhan  Bangalore         CS   24   6.9          6
6    Gita      Delhi         ME   21   8.0          7
7  Harish    Chennai        ECE   23   7.5          8

## 7. Selecting Rows

Two primary indexers:
- `.loc[]` — label-based selection (uses row/column **names**)
- `.iloc[]` — position-based selection (uses integer **positions**, like array indices)

In [35]:
df.loc[0]              # row by label

StudentID           1
Name            Aditi
Department         CS
Age                21
CGPA              8.5
City          Chennai
Name: 0, dtype: object

In [36]:
df.iloc[0]             # row by position

StudentID           1
Name            Aditi
Department         CS
Age                21
CGPA              8.5
City          Chennai
Name: 0, dtype: object

In [37]:
df.loc[0:3]            # label-based slicing (inclusive of end -- rows 0,1,2,3)

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
1          2    Bala        ECE   22   7.9    Delhi
2          3  Chitra         CS   21   9.1   Mumbai
3          4     Dev         ME   23   7.2     Pune

In [38]:
df.iloc[0:3]           # position-based slicing (exclusive of end -- rows 0,1,2)

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
1          2    Bala        ECE   22   7.9    Delhi
2          3  Chitra         CS   21   9.1   Mumbai

In [39]:
df.loc[[1, 3, 5]]      # select specific non-contiguous rows by label

   StudentID    Name Department  Age  CGPA       City
1          2    Bala        ECE   22   7.9      Delhi
3          4     Dev         ME   23   7.2       Pune
5          6  Farhan         CS   24   6.9  Bangalore

In [40]:
df.iloc[[1, 3, 5]]     # select specific non-contiguous rows by position

   StudentID    Name Department  Age  CGPA       City
1          2    Bala        ECE   22   7.9      Delhi
3          4     Dev         ME   23   7.2       Pune
5          6  Farhan         CS   24   6.9  Bangalore

## 8. Selecting Rows and Columns Together

In [41]:
df.loc[1, 'Name']                     # single cell by label

'Bala'

In [42]:
df.iloc[1, 1]                          # single cell by position

'Bala'

In [43]:
df.loc[0:3, ['Name', 'Department']]    # subset of rows and columns by label

     Name Department
0   Aditi         CS
1    Bala        ECE
2  Chitra         CS
3     Dev         ME

In [44]:
df.iloc[0:3, 0:3]                      # subset of rows and columns by position

   StudentID    Name Department
0          1   Aditi         CS
1          2    Bala        ECE
2          3  Chitra         CS

In [45]:
df.loc[:, 'Name':'Age']                # all rows, range of columns by label

     Name Department  Age
0   Aditi         CS   21
1    Bala        ECE   22
2  Chitra         CS   21
3     Dev         ME   23
4    Esha        ECE   22
5  Farhan         CS   24
6    Gita         ME   21
7  Harish        ECE   23

## 10. Conditional (Boolean) Row Selection

Rows can be filtered based on conditions applied to one or more columns. (A deeper treatment of filtering, sorting, and grouping is in the next session — this section builds the foundation.)

In [48]:
df[df['CGPA'] > 8]                             # single condition

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
2          3  Chitra         CS   21   9.1   Mumbai
4          5    Esha        ECE   22   8.8  Chennai

In [49]:
df[df['Department'] == 'CS']                   # equality condition

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
2          3  Chitra         CS   21   9.1     Mumbai
5          6  Farhan         CS   24   6.9  Bangalore

In [50]:
df[(df['CGPA'] > 7.5) & (df['Department'] == 'CS')]    # AND condition

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
2          3  Chitra         CS   21   9.1   Mumbai

In [51]:
df[(df['Department'] == 'CS') | (df['Department'] == 'ME')]   # OR condition

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi

In [52]:
df[df['Department'].isin(['CS', 'ME'])]        # isin() -- cleaner alternative to multiple OR conditions

   StudentID    Name Department  Age  CGPA       City
0          1   Aditi         CS   21   8.5    Chennai
2          3  Chitra         CS   21   9.1     Mumbai
3          4     Dev         ME   23   7.2       Pune
5          6  Farhan         CS   24   6.9  Bangalore
6          7    Gita         ME   21   8.0      Delhi

In [53]:
df[df['Age'].between(21, 22)]                  # between() -- range condition

   StudentID    Name Department  Age  CGPA     City
0          1   Aditi         CS   21   8.5  Chennai
1          2    Bala        ECE   22   7.9    Delhi
2          3  Chitra         CS   21   9.1   Mumbai
4          5    Esha        ECE   22   8.8  Chennai
6          7    Gita         ME   21   8.0    Delhi

In [54]:
df[~(df['Department'] == 'CS')]                # NOT condition using ~

   StudentID    Name Department  Age  CGPA     City
1          2    Bala        ECE   22   7.9    Delhi
3          4     Dev         ME   23   7.2     Pune
4          5    Esha        ECE   22   8.8  Chennai
6          7    Gita         ME   21   8.0    Delhi
7          8  Harish        ECE   23   7.5  Chennai

## 13. Hands-on Practice Exercise 1 — Basic CSV Operations

Using `students.csv`:

1. Read the CSV file into a DataFrame
2. Display the first 5 rows and the last 3 rows
3. Print `.shape`, `.columns`, `.dtypes`, and `.info()`
4. Find the number of unique departments and their frequency
5. Select the `Name` and `CGPA` columns only
6. Select rows 2 to 5 using both `.loc` and `.iloc`

In [59]:
# Write your solution here

## 14. Hands-on Practice Exercise 2 — Conditional Selection

Using `students.csv`:

1. Select all students with CGPA above 8
2. Select all students from the 'ECE' or 'ME' department using `isin()`
3. Select students aged between 21 and 23 using `between()`
4. Select the `Name` and `City` of all students with CGPA less than 7.5
5. Save the result of step 4 to a new CSV file named `low_cgpa_students.csv`

In [60]:
# Write your solution here

## 15. Hands-on Practice Exercise 3 — Working with a Real File

1. Read `students_missing.csv` and check how many missing values exist in each column using `.isnull().sum()`
2. Read `students_semicolon.csv` correctly using the right `sep` value
3. Read `students_no_header.csv` and assign proper column names
4. Compare the shapes of all the DataFrames you loaded — are they the same?

In [61]:
# Write your solution here

## Key Terms Glossary

| Term | Meaning |
|---|---|
| `read_csv()` | Function to load a CSV file into a DataFrame |
| `to_csv()` | Function to save a DataFrame as a CSV file |
| `sep` | Delimiter character used in the file |
| `header` | Row used as column names |
| `index_col` | Column used as row index |
| `usecols` / `nrows` / `skiprows` | Control which part of the file is loaded |
| `head()` / `tail()` / `sample()` | View rows of a DataFrame |
| `unique()` / `nunique()` / `value_counts()` | Explore distinct values in a column |
| `loc` | Label-based indexer |
| `iloc` | Integer position-based indexer |
| `at` / `iat` | Fast scalar (single value) access |
| `isin()` | Check membership in a list of values |
| `between()` | Check if values fall within a range |
| Boolean selection | Filtering rows using a condition |

## Common Mistakes to Avoid

- Forgetting `index=False` when saving to CSV (creates an unwanted extra `Unnamed: 0` column)
- Confusing `.loc[0:3]` (inclusive of end) with `.iloc[0:3]` (exclusive of end)
- Using `df['col1', 'col2']` instead of `df[['col1', 'col2']]` for multiple columns
- Forgetting the right `sep` value when a file uses a delimiter other than a comma
- Not checking `.info()` / `.isnull().sum()` after reading a CSV, missing wrong data types or missing values
- Using `header=None` without also providing `names=`, which leaves columns labeled `0, 1, 2...`

## Homework / Practice Assignment

1. Find or create any CSV dataset (minimum 15 rows, 5+ columns)
2. Load it into pandas and explore it fully: `.head()`, `.info()`, `.describe()`, `.shape`, `.dtypes`
3. Perform at least 3 different types of row selection (label-based, position-based, conditional)
4. Perform at least 2 different types of column selection
5. Save two different filtered subsets to new CSV files
6. Come prepared with 2 questions/doubts for the next session on filtering, sorting, and grouping